defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: sto3psl/dw-ci:1.4.0

cache: &cache
    key: v3-dependency-cache-{{ checksum "package-lock.json" }}

aliases:
    - &restore_source
      restore_cache:
          keys:
              - source-v1-{{ .Branch }}-{{ .Revision }}
              - source-v1-{{ .Branch }}-
              - source-v1-

version: 2

jobs:
    install:
        <<: *defaults
        steps:
            - *restore_source

            - checkout
            - save_cache:
                  key: source-v1-{{ .Branch }}-{{ .Revision }}
                  paths:
                      - '.git'
            - restore_cache:
                  key: v1-install-cache-{{ checksum "package-lock.json" }}

            - run:
                  name: Authenticate with registry
                  command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

            - run: npm ci

            - save_cache:
                  <<: *cache
                  paths:
                      - node_modules
                      - ~/.npm

            - save_cache:
                  key: v1-install-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ~/.npm

    lint:
        <<: *defaults
        steps:
            - *restore_source
            - checkout
            - restore_cache:
                  <<: *cache

            - run: npm run lint

workflows:
    version: 2
    install, test and lint:
        jobs:
            - install:
                  filters:
                      tags:
                          only: /^v.*/

            - lint:
                  filters:
                      tags:
                          only: /^v.*/
                  requires:
                      - install
