import purifyHtml from './purifyHtml';
import test from 'ava';
import { performance } from 'node:perf_hooks';

test('purifyHtml performance', t => {
    const iterations = 100_000;

    const t0 = performance.now();

    for (let i = 0; i < iterations; i++) {
        // Production chart https://app.datawrapper.de/table/mA8SD/visualize
        purifyHtml('6.0');
        purifyHtml('4.0');
        purifyHtml('3.0');
        purifyHtml('1.0');
        purifyHtml('2.0');
        purifyHtml('3.0');
        purifyHtml('6.0');
        purifyHtml('9.0');
        purifyHtml('19.0');
        purifyHtml('28.0');
        purifyHtml('34.0');
        purifyHtml('41.0');
        purifyHtml('47.0');
        purifyHtml('51.0');
        purifyHtml('60.0');
        purifyHtml('75.0');
        purifyHtml('84.0');
        purifyHtml('76.0');
        purifyHtml('74.0');
        purifyHtml('77.0');
        purifyHtml('70.0');
        purifyHtml('61.0');
        purifyHtml('50.0');
        purifyHtml('42.0');
        purifyHtml('31.0');
        purifyHtml('28.0');
        purifyHtml('25.0');
        purifyHtml('21.0');
        purifyHtml('22.0');
        purifyHtml('25.0');
        purifyHtml('23.0');
        purifyHtml('24.0');
        purifyHtml('23.0');
        purifyHtml('19.0');
        purifyHtml('16.0');
        purifyHtml('12.0');
        purifyHtml('8.0');
        purifyHtml('5.0');
        purifyHtml('3.0');
        purifyHtml('2.0');
        purifyHtml('1.0');
        purifyHtml('2.0');
        purifyHtml('3.0');
        purifyHtml('4.0');
        purifyHtml('6.0');
        purifyHtml('8.0');
        purifyHtml('9.0');
        purifyHtml('8.0');
        purifyHtml('10.0');
        purifyHtml('11.0');
        purifyHtml('13.0');
        purifyHtml('22.0');
        purifyHtml('29.0');
        purifyHtml('37.0');
        purifyHtml('44.0');
        purifyHtml('52.0');
        purifyHtml('54.0');
        purifyHtml('49.0');
        purifyHtml('46.0');
        purifyHtml('37.0');
        purifyHtml('25.0');
        purifyHtml('22.0');
        purifyHtml('20.0');
        purifyHtml('18.0');
        purifyHtml('25.0');
        purifyHtml('33.0');
        purifyHtml('46.0');
        purifyHtml('52.0');
        purifyHtml('56.0');
        purifyHtml('54.0');
        purifyHtml('66.0');
        purifyHtml('73.0');
        purifyHtml('72.0');
        purifyHtml('63.0');
        purifyHtml('57.0');
        purifyHtml('47.0');
        purifyHtml('45.0');
        purifyHtml('37.0');
        purifyHtml('32.0');
        purifyHtml('27.0');
        purifyHtml('21.0');
        purifyHtml('14.0');
        purifyHtml('17.0');
        purifyHtml('22.0');
        purifyHtml('27.0');
        purifyHtml('39.0');
        purifyHtml('42.0');
        purifyHtml('46.0');
        purifyHtml('60.0');
        purifyHtml('69.0');
        purifyHtml('59.0');
        purifyHtml('49.0');
        purifyHtml('41.0');
        purifyHtml('39.0');
        purifyHtml('31.0');
        purifyHtml('25.0');
        purifyHtml('26.0');
        purifyHtml('29.0');
        purifyHtml('44.0');
        purifyHtml('72.0');
        purifyHtml('100.0');
        purifyHtml('112.0');

        // Production chart https://app.datawrapper.de/table/uWZMZ/visualize
        purifyHtml('<style></style>', '<style>');
        purifyHtml('[ Insert title here ]', '');
        purifyHtml(
            '[ Insert title here ]',
            '<a><span><b><br><br/><i><strong><sup><sub><strike><u><em><tt>'
        );
        purifyHtml(
            '[ Insert title here ]',
            '<a><span><b><br><br/><i><strong><sup><sub><strike><u><em><tt>'
        );
        purifyHtml(
            '[ Insert title here ]',
            '<a><span><b><br><br/><i><strong><sup><sub><strike><u><em><tt>'
        );
        purifyHtml('ABC');
        purifyHtml('ABC1');
        purifyHtml('ABC2');
        purifyHtml('ABC3');
        purifyHtml('ABC4');
        purifyHtml('ABC5');
        purifyHtml('ABC6');
        purifyHtml('ABC7');
        purifyHtml('ABC8');
        purifyHtml('ABC9');
        purifyHtml('ABC10');
        purifyHtml('ABC11');
        purifyHtml('ABC12');
        purifyHtml('ABC13');
        purifyHtml('ABC14');
        purifyHtml('ABC15');
        purifyHtml('ABC16');
        purifyHtml('ABC17');
        purifyHtml('ABC18');
        purifyHtml('ABC19');
        purifyHtml('ABC20');
        purifyHtml('ABC21');
        purifyHtml('ABC22');
        purifyHtml('ABC23');
        purifyHtml('ABC24');
        purifyHtml('ABC25');
        purifyHtml('ABC26');
        purifyHtml('ABC27');
        purifyHtml('ABC28');
        purifyHtml('ABC29');
        purifyHtml('ABC30');
        purifyHtml('ABC31');
        purifyHtml('ABC32');
        purifyHtml('ABC33');
        purifyHtml('ABC34');
        purifyHtml('ABC35');
        purifyHtml('ABC36');
        purifyHtml('ABC37');
        purifyHtml('ABC38');
        purifyHtml('ABC39');
        purifyHtml('ABC40');
        purifyHtml('ABC41');
        purifyHtml('ABC42');
        purifyHtml('ABC43');
        purifyHtml('ABC44');
        purifyHtml('ABC45');
        purifyHtml('ABC46');
        purifyHtml('ABC47');
        purifyHtml('ABC48');
        purifyHtml('ABC49');
        purifyHtml('ABC50');
        purifyHtml('ABC51');
        purifyHtml('ABC52');
        purifyHtml('ABC53');
        purifyHtml('ABC54');
        purifyHtml('ABC55');
        purifyHtml('ABC56');
        purifyHtml('ABC57');
        purifyHtml('ABC58');
        purifyHtml('ABC59');
        purifyHtml('ABC60');
        purifyHtml('ABC61');
        purifyHtml('ABC62');
        purifyHtml('ABC63');
        purifyHtml('ABC64');
        purifyHtml('ABC65');
        purifyHtml('ABC66');
        purifyHtml('ABC67');
        purifyHtml('ABC68');
        purifyHtml('ABC69');
        purifyHtml('ABC70');
        purifyHtml('ABC71');
        purifyHtml('ABC72');
        purifyHtml('ABC73');
        purifyHtml('ABC74');
        purifyHtml('ABC75');
        purifyHtml('ABC76');
        purifyHtml('ABC77');
        purifyHtml('ABC78');
        purifyHtml('ABC79');
        purifyHtml('ABC80');
        purifyHtml('ABC81');
        purifyHtml('ABC82');
        purifyHtml('ABC83');
        purifyHtml('ABC84');
        purifyHtml('ABC85');
        purifyHtml('ABC86');
        purifyHtml('ABC87');
        purifyHtml('ABC88');
        purifyHtml('ABC89');
        purifyHtml('ABC90');
        purifyHtml('ABC91');
        purifyHtml('ABC92');
        purifyHtml('ABC93');
        purifyHtml('ABC94');
        purifyHtml('ABC95');
        purifyHtml('ABC');

        // Chart test span-multiple-rows
        purifyHtml('<style></style>', '<style>');
        purifyHtml('1110');
        purifyHtml('1590');
        purifyHtml('Mit Highend-Smartphone (z.B. Samsung Galaxy Z Fold2 5G):');
        purifyHtml('Vodafone Red XS');
        purifyHtml('30');
        purifyHtml('1710');
        purifyHtml('2430');
        purifyHtml('3150');
        purifyHtml('Vodafone Red S');
        purifyHtml('30');
        purifyHtml('1610');
        purifyHtml('2330');
        purifyHtml('3050');
        purifyHtml('Vodafone Red M/L');
        purifyHtml('50');
        purifyHtml('1450');
        purifyHtml('2650');
        purifyHtml('3850');
        purifyHtml('Telekom Magenta-<br/>Mobil S');
        purifyHtml('20');
        purifyHtml('1700');
        purifyHtml('2180');
        purifyHtml('2660');
        purifyHtml('Telekom Magenta-<br/>Mobil XL');
        purifyHtml('50');
        purifyHtml('1430');
        purifyHtml('2630');
        purifyHtml('3830');
        purifyHtml('nach&nbsp;2 Jahren');
        purifyHtml('nach&nbsp;4 Jahren');
        purifyHtml('nach&nbsp;6 Jahren');
        purifyHtml('Mit Mittelklasse-Smartphone (z.B. Samsung Galaxy A32 5G):');
        purifyHtml('Vodafone Red XS');
        purifyHtml('5');
        purifyHtml('170');
        purifyHtml('290');
        purifyHtml('410');
        purifyHtml('Vodafone Red S/M/L');
        purifyHtml('5');
        purifyHtml('121');
        purifyHtml('241');
        purifyHtml('361');
        purifyHtml('Telekom Magenta-<br/>Mobil S/M/L/XL');
        purifyHtml('10');
        purifyHtml('241');
        purifyHtml('481');
        purifyHtml('721');
        purifyHtml('Mit Oberklasse-Smartphone (z.B. iPhone 12):');
        purifyHtml('Vodafone Red XS');
        purifyHtml('20');
        purifyHtml('930');
        purifyHtml('1410');
        purifyHtml('1890');
        purifyHtml('Vodafone Red S');
        purifyHtml('30');
        purifyHtml('920');
        purifyHtml('1640');
        purifyHtml('2360');
        purifyHtml('Vodafone Red M/L');
        purifyHtml('30');
        purifyHtml('770');
        purifyHtml('1490');
        purifyHtml('2210');
        purifyHtml('Telekom Magenta-<br/>Mobil S');
        purifyHtml('20');
        purifyHtml('900');
        purifyHtml('1380');
        purifyHtml('1860');
        purifyHtml('Telekom Magenta-<br/>Mobil XL');
        purifyHtml('20');
        purifyHtml('630');
        purifyHtml('1110');
        purifyHtml('1590');
        purifyHtml('Mit Highend-Smartphone (z.B. Samsung Galaxy Z Fold2 5G):');
        purifyHtml('Vodafone Red XS');
        purifyHtml('30');
        purifyHtml('1710');
        purifyHtml('2430');
        purifyHtml('3150');
        purifyHtml('Vodafone Red S');
        purifyHtml('30');
        purifyHtml('1610');
        purifyHtml('2330');
        purifyHtml('3050');
        purifyHtml('Vodafone Red M/L');
        purifyHtml('50');
        purifyHtml('1450');
        purifyHtml('2650');
        purifyHtml('3850');
        purifyHtml('Telekom Magenta-<br/>Mobil S');
        purifyHtml('20');
        purifyHtml('1700');
        purifyHtml('2180');
        purifyHtml('2660');
        purifyHtml('Telekom Magenta-<br/>Mobil XL');
        purifyHtml('50');
        purifyHtml('1430');
        purifyHtml('2630');
        purifyHtml('3830');
        purifyHtml('nach&nbsp;2 Jahren');
        purifyHtml('nach&nbsp;4 Jahren');
        purifyHtml('nach&nbsp;6 Jahren');
    }

    const duration = performance.now() - t0;
    t.log(`purifyHtml performance test done in ${duration.toFixed(4)} ms`);
    t.pass();
});
