#!/bin/sh
# read version from package.json
VERSION=$(python -c 'import json;print json.loads(open("../package.json").read())["version"]')
# remove old javascript
rm ../www/static/js/datawrapper*.js
# generate javascript to be included on datawrapper
cat dw.core.js dw.dataset.js dw.utils.js dw.chart.js dw.chart.editable.js dw.theme.js dw.parsers.delimited.js dw.visualization.js > tmp.js
uglifyjs tmp.js > ../www/static/js/datawrapper-backend-$VERSION.min.js
# generate js that's packed with each chart
cat dw.core.js dw.dataset.js dw.chart.js dw.theme.js dw.parsers.delimited.js dw.visualization.js > tmp.js
uglifyjs tmp.js > ../www/static/js/datawrapper.min.js
mv tmp.js ../www/static/js/datawrapper.js

# if coffeescript is installed, generate javascript for user's administration
if type "coffee" >/dev/null 2>&1; then
	coffee -b -c -o ../www/static/js/ dw.admin.users.coffee
fi
