#!/bin/sh
VERSION=$(python -c 'import json;print json.loads(open("../package.json").read())["version"]')
cat dw.core.js dw.dataset.js dw.ui.js dw.chart.js dw.chart.editable.js dw.theme.js dw.parsers.delimited.js dw.visualization.js > tmp.js
uglifyjs tmp.js > ../www/static/js/datawrapper-backend-$VERSION.min.js
cat dw.core.js dw.dataset.js dw.chart.js dw.theme.js dw.parsers.delimited.js dw.visualization.js > tmp.js
uglifyjs tmp.js > ../www/static/js/datawrapper-$VERSION.min.js
rm tmp.js
